import '@/styles/index.scss'
import {getServerSession} from 'next-auth'
import {authOptions} from '@/pages/api/auth/[...nextauth]'
import SessionProvider from '@/modules/SessionProvider'
import SideBar from '@/modules/sidebar/SideBar'
import LoginPage from '@/modules/loginPage/LoginPage'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang='en'>
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <LoginPage />
          ) : (
            <div className='layout_wrapper'>
              <div className='sidebar'>
                <SideBar />
              </div>

              <div className='layout_child_wrapper'>{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
